apiVersion: v1
data:
  URI: b2NpOi8vcmVnaXN0cnkucmVkaGF0LmlvL3JoYWkvbW9kZWxjYXItbWluaXN0cmFsLTMtM2ItaW5zdHJ1Y3QtMjUxMjozLjA=
kind: Secret
metadata:
  annotations:
    opendatahub.io/connection-hidden: "true"
    opendatahub.io/connection-type-protocol: uri
    opendatahub.io/connection-type-ref: uri-v1
    openshift.io/display-name: secret-wpxq4p
  labels:
    opendatahub.io/dashboard: "true"
  name: secret-wpxq4p
  namespace: demo
type: Opaque
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    modelFormat: vLLM
    opendatahub.io/connections: secret-wpxq4p
    opendatahub.io/hardware-profile-name: 1gpu
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/model-type: generative
    openshift.io/description: ""
    openshift.io/display-name: RedHatAI/Ministral-3-3B-Instruct-2512
    security.opendatahub.io/enable-auth: "false"
    serving.kserve.io/deploymentMode: Standard
    serving.kserve.io/stop: "false"
  generation: 1
  labels:
    networking.kserve.io/visibility: exposed
    opendatahub.io/dashboard: "true"
    opendatahub.io/genai-asset: "true"
  name: redhataiministral-3-3b-instruc
  namespace: demo
spec:
  predictor:
    automountServiceAccountToken: false
    deploymentStrategy:
      type: Recreate
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
      - --max-model-len=-1
      env:
      - name: VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS
        value: "1"
      modelFormat:
        name: vLLM
      name: ""
      resources:
        limits:
          cpu: "1"
          memory: 4Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 4Gi
          nvidia.com/gpu: "1"
      runtime: redhataiministral-3-3b-instruc
      storageUri: oci://registry.redhat.io/rhai/modelcar-ministral-3-3b-instruct-2512:3.0
    timeout: 30
---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
#    opendatahub.io/runtime-version: v0.18.0
    opendatahub.io/runtime-version: v0.24.0
    opendatahub.io/serving-runtime-scope: global
    opendatahub.io/template-display-name: vLLM NVIDIA GPU ServingRuntime for KServe
    opendatahub.io/template-name: vllm-cuda-runtime-template
    openshift.io/display-name: vLLM NVIDIA GPU ServingRuntime for KServe
  generation: 1
  labels:
    opendatahub.io/dashboard: "true"
  name: redhataiministral-3-3b-instruc
  namespace: demo
spec:
  annotations:
    opendatahub.io/kserve-runtime: vllm
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  containers:
  - args:
    - --port=8080
    - --model=/mnt/models
    - --served-model-name={{.Name}}
    command:
    - python
    - -m
    - vllm.entrypoints.openai.api_server
    env:
    - name: HF_HOME
      value: /tmp/hf_home
    image: registry.redhat.io/rhaii/vllm-cuda-rhel9@sha256:5800e12b2a465f15961fcf34b645d79ed4f91ec9161eab22b1205d12682183c8
    name: kserve-container
    ports:
    - containerPort: 8080
      protocol: TCP
  multiModel: false
  supportedModelFormats:
  - autoSelect: true
    name: vLLM
