apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/accelerator-name: 1gpu
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/runtime-version: v0.10.1.1
    opendatahub.io/serving-runtime-scope: global
    opendatahub.io/template-display-name: vLLM NVIDIA GPU ServingRuntime for KServe
    opendatahub.io/template-name: vllm-cuda-runtime
    openshift.io/display-name: tinyllama
#  creationTimestamp: "2026-09-06T20:18:12Z"
#  generation: 1
  labels:
    opendatahub.io/dashboard: "true"
  name: tinyllama
  namespace: demo
#  resourceVersion: "69472"
#  uid: 84b6194f-03bd-4740-9cb5-7abd8bd0a3ef
spec:
  annotations:
    opendatahub.io/kserve-runtime: vllm
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  containers:
  - args:
    - --port=8080
    - --model=/mnt/models
    - --served-model-name={{.Name}}
    command:
    - python
    - -m
    - vllm.entrypoints.openai.api_server
    env:
    - name: HF_HOME
      value: /tmp/hf_home
    image: registry.redhat.io/rhoai/odh-vllm-cuda-rhel9@sha256:ca0bf2704b8d6ad958ce2e91a469e01a86a42c837eded349d369123ed6b7c349
    name: kserve-container
    ports:
    - containerPort: 8080
      protocol: TCP
    volumeMounts:
    - mountPath: /dev/shm
      name: shm
  multiModel: false
  supportedModelFormats:
  - autoSelect: true
    name: vLLM
  volumes:
  - emptyDir:
      medium: Memory
      sizeLimit: 2Gi
    name: shm
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: tinyllama
    serving.kserve.io/deploymentMode: RawDeployment
#  creationTimestamp: "2026-09-06T20:18:12Z"
#  finalizers:
#  - inferenceservice.finalizers
#  - odh.inferenceservice.finalizers
#  generation: 1
  labels:
    networking.kserve.io/visibility: exposed
    opendatahub.io/dashboard: "true"
  name: tinyllama
  namespace: demo
#  resourceVersion: "75488"
#  uid: ff0c5294-463a-4bdd-ad64-3c1746015aca
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ""
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 4Gi
          nvidia.com/gpu: "1"
      runtime: tinyllama
      storageUri: oci://quay.io/rh-aiservices-bu/tinyllama:1.0
#status:
#  address:
#    url: http://tinyllama-predictor.demo.svc.cluster.local
#  components:
#    predictor: {}
#  conditions:
#  - lastTransitionTime: "2026-09-06T20:18:12Z"
#    status: "True"
#    type: IngressReady
#  - lastTransitionTime: "2026-09-06T20:27:42Z"
#    status: "True"
#    type: PredictorReady
#  - lastTransitionTime: "2026-09-06T20:27:42Z"
#    status: "True"
#    type: Ready
#  - lastTransitionTime: "2026-09-06T20:18:12Z"
#    severity: Info
#    status: "False"
#    type: Stopped
#  deploymentMode: RawDeployment
#  modelStatus:
#    copies:
#      failedCopies: 0
#      totalCopies: 1
#    states:
#      activeModelState: Loaded
#      targetModelState: Loaded
#    transitionStatus: UpToDate
#  observedGeneration: 1
#  url: https://tinyllama-demo.apps.ocp2x.king.lab
